 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: oms-kroger-ingress
   annotations:
     ingress.bluemix.net/sticky-cookie-services: "serviceName=oms-dev-ibm-oms-ent-prod name=ingress_ssfs expires=2h path=/ hash=sha1"
 spec:
   tls:
   - hosts:
     - dev.oms-on-ocp-kroger.us-east.containers.appdomain.cloud
     secretName: oms-on-ocp-kroger
   rules:
   - host: dev.oms-on-ocp-kroger.us-east.containers.appdomain.cloud
     http:
       paths:
       - path: /
         backend:
           serviceName: oms-dev-ibm-oms-ent-prod
           servicePort: 9080
